# Teleop configuration for PS4 joystick using the x-pad configuration.
teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 2.0
  axis_angular: 0
  scale_angular: 1.4
  enable_button: 4
  enable_turbo_button: 5
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/ds4x
